name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'outputs/curve25519_functions.csv'
      - 'scripts/plot_*.py'
      - '.github/workflows/deploy-pages.yml'
  workflow_dispatch:

# Sets permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full git history needed for temporal charts

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install matplotlib pandas gitpython beartype

      - name: Generate charts
        run: |
          scripts/plot_progress.py
          scripts/plot_progress_over_time.py --max-commits 200 --sample 3
          scripts/plot_csv_preview.py

      - name: Copy charts and CSV to docs
        run: |
          mkdir -p docs/outputs
          cp outputs/verification_funnel.png docs/outputs/
          cp outputs/absolute_counts_over_time.png docs/outputs/
          cp outputs/module_breakdown.png docs/outputs/
          cp outputs/csv_preview.png docs/outputs/
          cp outputs/curve25519_functions.csv docs/outputs/
          cp outputs/metadata.json docs/outputs/
          cp outputs/stats.json docs/outputs/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

